title: Cangkerkopi
description: 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: ""

markdown: kramdown

plugins:
  - jekyll-paginate-v2

collections:
  projects: 
    output: true


defaults:
  - scope: 
      type: posts
    values: 
      layout: post
      permalink: /blog/:title
      active_menu: post
  - scope: 
      type: projects
    values: 
      layout: project
      permalink: /proyek/:title
      active_menu: project
  - scope: 
      path: "pages"
    values: 
      layout: page
  - scope: 
      path: ""
    values: 
      active_menu: home

pagination:
  enabled: true
  collection: 'posts'
  per_page: 12

  permalink: '/:num/'

  sort_field: 'date'

  trail: 
    before: 2
    after: 2